#

application:
  namespace: smarter
  appName: smarter-device-manager

image:
  repository: registry.gitlab.com/smarter-project/smarter-device-manager
  #repository: registry.gitlab.com/smarter-project/smarter-device-manager
  # @default -- chart.appVersion
  tag: ""
  pullPolicy: IfNotPresent
