{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.appName }}
  namespace: {{ .Values.application.namespace }}
data:
  conf.yaml: |
  {{- toYaml .Values.config | nindent 4 }}
{{- end }}
